//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMvcFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTable
    {
        public int stockId { get; set; }
        public string stockName { get; set; }
        public string stockDescription { get; set; }
        public double unitPrice { get; set; }
    }
}
